### ISSUE TITLE
OpenCL: secp256k1_extended.cl no longer self-contained for embed consumers — the #335 Metal breakage, reproduced in OpenCL

### ISSUE THREAD

**Issue by craigraw** [shrec/UltrafastSecp256k1#415]
Found while validating the CUDA and OpenCL backends of duckdb-ufsecp-extension against
`dev` @ `17fceb76` (RTX 5080, driver 580.173.02, CUDA 13.1, Ubuntu x86-64). CUDA first,
since it's the short part: **100% correct with zero changes** — both 10.3M-row full-match
databases, testnet4 and mainnet documented scans all exact, GPU timing flat vs v3.68.0.
And the x86-64 CPU path is 5.6% *faster* than v3.68.0 at the same commit, consistent
with #336's resolution. OpenCL is the problem.

## The regression

Our extension embeds 6 OpenCL kernel files (`field`, `point`, `gen_table_w8`, `extended`,
`affine`, `bip352`), strips `#include` lines, and compiles the concatenation at runtime —
the OpenCL analogue of the Metal embed from #335. At v4.5.0 this was still self-contained
(I verified that during the original evaluation). At current `dev` it is not:
`src/opencl/kernels/secp256k1_extended.cl` now pulls in the constant-time suite

```
secp256k1_extended.cl:1207: #include "secp256k1_ct_ops.cl"
secp256k1_extended.cl:1208: #include "secp256k1_ct_field.cl"
secp256k1_extended.cl:1209: #include "secp256k1_ct_scalar.cl"
secp256k1_extended.cl:1210: #include "secp256k1_ct_point.cl"
```

and calls it from the ECDSA/Schnorr/ECDH sign paths (call sites around lines 1311, 1513,
1565, 1792). With includes stripped, the NVIDIA driver rejects the embedded source:

```
<kernel>:3348:5: error: unknown type name 'CTJacobianPoint'; did you mean 'JacobianPoint'?
<kernel>:3349:5: warning: implicit declaration of function 'ct_generator_mul_impl' is invalid in OpenCL
<kernel>:3350:23: warning: implicit declaration of function 'ct_point_to_jacobian' is invalid in OpenCL
<kernel>:3366:5: warning: implicit declaration of function 'ct_scalar_inverse_impl' is invalid in OpenCL
<kernel>:3832:5: warning: implicit declaration of function 'ct_jacobian_to_affine' is invalid in OpenCL
… 7 warnings and 7 errors generated.
```

Undefined: `ct_generator_mul_impl`, `ct_point_to_jacobian`, `ct_scalar_inverse_impl`,
`ct_jacobian_to_affine`, and the type `CTJacobianPoint`. A v3.68.0 build on the same
machine compiles the same embed cleanly, so this arrived with the v4.x ct work —
specifically after v4.5.0.

This is exactly the failure mode you fixed for Metal in #335 (`SECP256K1_METAL_SCAN_ONLY`,
completed in the `2d6de776`-era gates): a scan-only consumer embeds the extended file for
its field/point math and never dispatches the sign kernels, but the sign wrappers'
callees now live in files it doesn't embed, and OpenCL — like Metal's AIR — won't
dead-strip functions with unresolved callees.

## Request

The same remedy as #335: a `SECP256K1_OPENCL_SCAN_ONLY` (or shared `SECP256K1_GPU_SCAN_ONLY`)
guard in `secp256k1_extended.cl` that excludes the four `ct_*.cl` includes, the sign-path
wrappers that call into them, and the sign kernels — leaving the file self-contained for
a scan-only embed, with the default build unchanged.

Two smaller observations from the same run, take or leave:

1. This is the second instance of the same class in three months. A cheap CI guard would
   catch the whole class: compile the scan-only embed subset (the 6 files, includes
   stripped, gate defined) with any OpenCL syntax checker — even `clang -x cl
   -fsyntax-only` — per PR. Happy to share our exact embed concatenation order if useful.
2. v4's `opencl_context.cpp` added `clGetKernelWorkGroupInfo` (work-size probing). Not a
   bug — but consumers that provide `cl*` trampolines over `dlopen` rather than linking
   libOpenCL will each need to add it; ours was a 3-line fix. Mentioning it here so it's
   findable.

Same offer as always: the RTX 5080 box reproduces this in ~a minute, and the 10.3M-row
correctness databases are ready — glad to validate a patch quickly.

**Comment by shrec** [comment]
thanks i will look on it and will fix and infrom you

**Comment by craigraw** [comment]
Confirming the fix on hardware — ran the full re-validation on the RTX 5080 box against
`775a53ad` ("release: v4.6.0", contains `8ab349b2`).

| | before (`17fceb76`) | after (`775a53ad`) |
|---|---|---|
| Fused kernel compile (NVIDIA 580.173.02) | 7 errors, silent fallback | **compiles clean** |
| 10.3M-row correctness (base-output) | 1,278,287 (12.4%) | **10,311,319 (100%)** |
| 10.3M-row correctness (change-label) | not reached | **10,312,725 (100%)** |
| mainnet documented scan | not reached | exactly the 4 expected |

Consumer-side, the gate is a one-line seed of the embedded source
(`#define SECP256K1_OPENCL_SCAN_ONLY 1` ahead of the concatenation), mirroring the Metal
define. Fused-vs-fused timing against a v3.68.0 build on the same machine is flat
(12.97s vs 12.60s on a 178M-row scan, within noise). Also nice to see the
embed-closure check land as a permanent regression test.

Two observations, take or leave:
1. The cold-cache compile of the embedded kernel roughly doubled with the file growth:
   109 s (v3.68.0) → 212 s (v4.6.0) on this driver, measured with `CUDA_CACHE_PATH`
   pointed at an empty directory. It's one-time per source×driver×device (the NVIDIA
   ComputeCache brings warm starts to ~0.4 s; the v4 entry is 136 MB), so not a per-start
   cost — but a cold start can look like a hang, and might be worth a line in the kernel
   docs alongside the growth.
2. As of 2026-09-22 there's no `v4.6.0` tag on the repo despite the release commit —
   assuming that's just not pushed yet. We'd pin the tag for our upgrade once it exists.

Thanks for the quick turnaround — from our side #415 is fully resolved.
